name: npm unused packages checker
  uses: dtimskr/discord-stats-tracker
  with:
    # list of Glob patterns for paths to ignore
    IGNORE_PATTERNS: # optional, default is 
    # list of packages that exist in package.json and not used in the code to ignore and mark them as used
    IGNORE_PACKAGES: # optional, default is 
